version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres

  ubi-service:
    build: ./ubi-service
    ports:
      - "8084:8084"
    depends_on:
      - postgres

  audit-service:
    build: ./audit-service
    ports:
      - "8085:8085"
    volumes:
      - ./audit.db:/audit.db

  frontend-service:
    build: ./frontend-service
    ports:
      - "8080:8080"
    volumes:
      - ./frontend-service/templates:/templates

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: xbank_user
      POSTGRES_PASSWORD: xbank_pass
      POSTGRES_DB: xbank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
