[package]
name = "transaction-service"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-actix-native-tls", "postgres", "offline"] }
