[package]
name = "frontend-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
maud = { version = "0.23.0", features = ["axum"] }  # Enable axum feature for maud
tokio = { version = "1.0", features = ["full"] }